# Generated by Django 2.2.4 on 2019-12-08 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfUsers', models.IntegerField(blank=True, default=0)),
                ('authUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('travel', models.IntegerField(blank=True, null=True)),
                ('attrition', models.IntegerField(blank=True, null=True)),
                ('dr', models.IntegerField(blank=True, null=True)),
                ('department', models.IntegerField(blank=True, null=True)),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('ed', models.IntegerField(blank=True, null=True)),
                ('education', models.IntegerField(blank=True, null=True)),
                ('envsatisfaction', models.IntegerField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('hourlyRate', models.IntegerField(blank=True, null=True)),
                ('involvment', models.IntegerField(blank=True, null=True)),
                ('joblevel', models.IntegerField(blank=True, null=True)),
                ('role', models.IntegerField(blank=True, null=True)),
                ('satisfaction', models.IntegerField(blank=True, null=True)),
                ('marital_status', models.IntegerField(blank=True, null=True)),
                ('income', models.IntegerField(blank=True, null=True)),
                ('monthly_rate', models.IntegerField(blank=True, null=True)),
                ('prevCompanies', models.IntegerField(blank=True, null=True)),
                ('overage', models.IntegerField(blank=True, default=1, null=True)),
                ('overtime', models.IntegerField(blank=True, null=True)),
                ('salaryHike', models.IntegerField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, max_length=50, null=True)),
                ('relsatisfaction', models.IntegerField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('workingYears', models.IntegerField(blank=True, null=True)),
                ('lastTrainingTime', models.IntegerField(blank=True, null=True)),
                ('workLifeBalance', models.IntegerField(blank=True, null=True)),
                ('yearsAtCompany', models.IntegerField(blank=True, null=True)),
                ('yearsInCurrentRole', models.IntegerField(blank=True, null=True)),
                ('lastprom', models.IntegerField(blank=True, null=True)),
                ('curManager', models.IntegerField(blank=True, null=True)),
                ('empUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('senior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loginsignup.Authority')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lastDate', models.DateField()),
                ('completedDate', models.DateField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('auth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loginsignup.Authority')),
                ('emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loginsignup.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('auth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loginsignup.Authority')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
